version: "3.8"
services:

  jbc-execution:
    container_name: jbc-execution
    image: ethereum/client-go:v1.13.5
    user: root
    entrypoint: /root/geth-script.sh
    command:
      - "--datadir=/datadir/geth"
      - "--networkid=${NETWORK_ID}"
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/config/jwt.hex
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,engine,web3,net
      - --http.port=8545
      - --http.corsdomain=*
      - --http.vhosts=*
    volumes:
      - ./genesis.json:/genesis.json
      - ./data:/datadir
      - ./geth-script.sh:/root/geth-script.sh
      - ./config:/config
    ports:
      - 30303:30303
      - 8545:8545
    restart: always

  jbc-consensus:
    container_name: jbc-consensus
    image: consensys/teku:latest
    user: root
    command:
      - --network=/config/config-teku.yaml
      - --genesis-state=/config/genesis.ssz
      - --ee-endpoint=http://jbc-execution:8545
      - --ee-jwt-secret-file=/config/jwt.hex
      - --data-path=/data
      - --p2p-subscribe-all-subnets-enabled
      - --p2p-static-peers=/ip4/119.59.105.149/tcp/9100/p2p/16Uiu2HAm1MC8f9XYZFjhYTTNa5oXxHk8MfPgERRW3ChTU76CM4hD,/ip4/65.21.110.118/tcp/9100/p2p/16Uiu2HAmBx33yrw1krm2mJUfuSM6LYmYHdLQuNXbABWzHuMTGBzY,/ip4/119.59.105.141/tcp/9100/p2p/16Uiu2HAmEkYUad8TGYcnFnXecyRngqywPG6BJ8LaxvRYxVybw8nm
      - --p2p-discovery-bootnodes=enr:-MS4QFW6lzwqhUi80uoVthN3KayudKkERvW2IqQVl61fk56FEW_mhvYXNCOSJS5wZnbIBKT04hu9v19qSN7xOJBLj95yh2F0dG5ldHOIgAEAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhHc7aY2EcXVpY4IjjYlzZWNwMjU2azGhAx8jmkBO4YOOod30TevUoiWT89UKZ8bnWqRd1XXILl1qiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM
      - --ignore-weak-subjectivity-period-enabled
    volumes:
      - ./data/teku:/data
      - ./config:/config
    ports:
      - 0.0.0.0:13000:13000/tcp
      - 0.0.0.0:13000:13000/udp
    restart: always
