version: "3.8"
services:

  jbc-execution:
    container_name: jbc-execution
    image: hyperledger/besu:latest
    user: root
    command:
      - --genesis-file=/genesis.json
      - --data-path=/datadir/besu
      - --rpc-ws-enabled
      - --rpc-http-enabled
      - --engine-jwt-secret=/config/jwt.hex
      - --engine-host-allowlist=*
      - --p2p-host=0.0.0.0
      - --p2p-interface=0.0.0.0
      - --host-allowlist=*
      - --Xdns-enabled=true
      - --nat-method=docker
      - --bootnodes=enode://f06e9a7b61376bcd95df21cd6f624c46c62c8fe5b18faa96d85542bb08aa3af0c0726291cab36f30917e34ab35e0ba064ac811f5c4ac7e836d2ce95447975d5e@135.181.4.243:32323,enode://af679fdd2c099223a3a7eb361c45467bbd8f38bbceccb10775ae2a41c933c9edfd751f0df52faab356644c9ce7fe7cdfd091b9570da1384d16468901d6128c28@88.198.230.131:32323,enode://d72f4e721c183842339728da3ee63d4406bed2ce61bb053d613ccf3ccbae1fffaedeb3285675d0889577e0d284e61d1b240897c7bedadaf188bb7cdd89a55aa3@65.21.192.220:32323,enode://5519975ec8e34998d7d0a043facb1b355e3cad7f1ce7e9ba8e7527ef1d42be2a851382b7f2b8803391ea6b7c8e39f8921ce58452a540cc26c5d21861489629c8@65.21.194.198:32323,enode://78afa4dcdaac345d66fc13c1962ac2f16d1ea6769022a882cb0eda66e32c2887698ea1215d453764545e73e68559cc2fd1e9f202b18262a0d602267f04d5f261@95.217.58.14:32323,enode://a8f25666194c5d56516168040322f8a8a5dd501fff549845f8fce06f64f8553feec6fbacb70aa4e85f7a9361351e454e8498c817a227a854b9104a8dcb4c8ee7@94.130.222.145:32323,enode://b22a53a06bde223260ab9b0547fbe762ae4e22a15045df2302a5d4d804fd91889a235098c774afd0cde9ebdde9ff9cc88f9e4a0ccbf792fe6a76665eef66f028@195.201.105.166:32323,enode://fb6d8e33fa16949995c5f20479948bda9ede515334331da39e8e099053f563ac3472eddd29ecbe34a5088af0dec09b034617ad74181179084fbdf80fb37c323a@65.108.75.252:32323,enode://a94483cecbcd07fa8b1610af4b10586c650665679544a77bf57d0b6abfc5f6aec335a6e0e2cab4235599707cac3496f6d28b08806a169539a53021485aaf792c@65.108.120.116:32323,enode://0cb1d60e40aa5dcd83a91f7c4aab4e8c53fcbe64b6a0127b6b30ce54838c1f68b46d60a344d88fdb4335eace67343ed04a8a60d2ebe7f8a5c4d5534366c5d29c@65.108.195.126:32323,enode://5d8e4f7d49b3ccd6a1482afe8475300b80f6283352b1c8f3f55c7098c92c6f84bc19a6e97748676921785d5672b7023ae9896908c47a519424035159e6ed8077@65.108.201.210:32323,enode://e674c17f9fbad5d5b8776fd9aab48d958b972f48b28c3d2ae0cb3e238f058cafc1d4996b0936bbe26dbfb4b94f80bc80ad425d5d37ca2fe2d241c60ca0bcaf50@135.181.62.40:32323,enode://d370724b1ceff14ef55a23098b21b4182a6b9743d48ee3cee539d662b051ff0452a27aaef7f43da8312f66f9c3cbd3201420b6145bbfe1544b4cd99b412d798a@95.217.122.150:32323
    volumes:
      - ./genesis.json:/genesis.json
      - ./data:/datadir
      - ./config/static-nodes.json:/datadir/besu/static-nodes.json
      - ./config:/config
    ports:
      - 8545:8545
      - 0.0.0.0:30303:30303/tcp
      - 0.0.0.0:30303:30303/udp
      - 0.0.0.0:9000:8000/tcp
      - 0.0.0.0:9000:9000/udp

    restart: always


  jbc-consensus:
    container_name: jbc-consensus
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    user: root
    command:
      - --chain-config-file=/config/config.yaml
      - --genesis-state=/config/genesis.ssz
      - --chain-id=${NETWORK_ID}
      - --datadir=/data
      - --contract-deployment-block=2176957
      - --chain-id=8899
      - --minimum-peers-per-subnet=0
      - --enable-debug-rpc-endpoints
      - --jwt-secret=/config/jwt.hex
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --chain-config-file=/config/config.yaml
      - --genesis-state=/config/genesis.ssz
      - --chain-id=${NETWORK_ID}
      - --datadir=/data 
      - --jwt-secret=/config/jwt.hex
      - --rpc-host=0.0.0.0 
      - --grpc-gateway-host=0.0.0.0 
      - --monitoring-host=0.0.0.0
      - --bootstrap-node=enr:-MS4QO7nnkhvlmO8PjGbX89mCWKoB8RVmvm3yYrlchLWW1lpEsfT0ONYqezLoPLtbJyeMHHXdB1Y0T3Se6KdUF4SXyYTh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhIe1BPOEcXVpY4IjjYlzZWNwMjU2azGhAqAFlsx85u3GpSrGQ7Q0Vdgb8OCyvQYcJqgkfF57TPr-iHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QIwO0sSQdahvgPa8UlFBXV08pfRgsue7W_KlkcHfB4mbBbDrHAfpPlU8u3DXr2_ixHCqRGkkDXu5osJiJUN97G0Qh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhFjG5oOEcXVpY4IjjYlzZWNwMjU2azGhAzwikSxEp5_DivEM4y6byo715UzqwHwZAp0q3i8NYpTxiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QB9GpZD2SygbX7KByaW55l7S0p3FGAvxLbYrgUiRoFcHU9XZDQI6zMxRi64syMHxGiK8f0L1m9yIzaFgUh2Ld-wNh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhEEVwNyEcXVpY4IjjYlzZWNwMjU2azGhA28nHNdJuzEef0O-Y0vpUuCAqqJixKDy-k3hWQr4THD6iHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QAVkgWC0lg43GNi5t76pim5yJsqZgnT_HI0QzZmmsfUbLVxeZwP54Tv5jX1kyr8295fDevjjK1L7N2MxN3v1OycEh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhEEVwsaEcXVpY4IjjYlzZWNwMjU2azGhAm-JkY-JJ2ikAxNgvlK41IxG7GVYiW21Qg4jdn4gDgaCiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QL5I43Gm89DXsQY5YeDdKHyNCXst_YhTsB4nFjdg2-B0GixOC-ZMesJlLfrhj-Kiu7OMrT5ylooVnKOlQ0WLNqMOh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhF_ZOg6EcXVpY4IjjYlzZWNwMjU2azGhAmcg3uon6pHcIFyu9YZ5YecjQzzDFODdu4azseJffXtZiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QBGksw7SJl5Vt2ID-9PinTc0WKjdOZJQOzqdPN5xoy-OJTei-kub3l_Y75y9vI6lGq9dj1tqRSCqM9dsufSuFfwNh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhF6C3pGEcXVpY4IjjYlzZWNwMjU2azGhA7t0KXG_vZf7AyZ_HeGWDM7PHxInwYkFo7D63spS2MvliHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QFKB8W_MmHLZQtvc-20v7BsFg1j6MIfvxSYaYPGk6Z8aALu8KjGtdDmaG4lBnTCFGc0ASy8OMLjdSkmiUgMFr2QEh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhMPJaaaEcXVpY4IjjYlzZWNwMjU2azGhArpfoVPPePJdNZ8mOAa_-d9Z5kKc2Ged6KZlnn6wP7FPiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QBoYhwy-NTmmpAYJJ2isdVxJ3oZ40OfEfPG1S2C4irJIdj7GuOK3GCueoQJX0BxpGKquhn6fYBbzXvsjFiZ9ISUEh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhEFsS_yEcXVpY4IjjYlzZWNwMjU2azGhA99ojsASmqaD00ClocBRn9bGGLYHoO4lgBKMUMdnFIzIiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QPwUJVI5JcSCq6l8zBsNRU_dJgJOxJa8mJt-Fo9pCFpTIxczXzE3gsKW3F6lBux5y8e1baj7NHDO4Xu4hHwoGnsPh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhEFseHSEcXVpY4IjjYlzZWNwMjU2azGhAlfRbk8emZxrLAQ4CK3bjz1z2Uzd8BXEQiNRSsGcaQSPiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QEJHYd8PS1XwoqvaC7EsopJzX15BhWc_awfARkAkC8LDAJyP2oHZ_0X7HHn0H2rTj9iQwcNAQXfInu5KISAZ2MsHh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhEFsw36EcXVpY4IjjYlzZWNwMjU2azGhAqBZMAhpY-HDiRu88T-vSXYym07hZoLz-bMT08a8RKwoiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QNJIa24yHtUxoQO_Xp9qEZsrbsuG-wYDhzNlFalDhdHsBLcOi2AUsG3vSeAYpTrVl_2ZMXZsUnf3jv8h1p043OgEh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhEFsydKEcXVpY4IjjYlzZWNwMjU2azGhA9Wten_DWVK3aUuVfJyqwV9L53pQsBl_V9BQ6lTh2Nd7iHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QMEiRrcvs_XIFzUkvFXedhceYBzwSrH8GkrYRnmpGi67TsyS7ss1T8rVzW8MhwKHVvNYUp5Xa_tjTBOM7_qv2sIEh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhIe1PiiEcXVpY4IjjYlzZWNwMjU2azGhA0IRaEEacgxwPsdXTXkRWuKO-sh36F3PtzR8Z1TawKuAiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM,enr:-MS4QLciafMSIpmQ21-E-aOQH3mJwqO6pcq-SoZQuoEJbDxXS0sUSRQDWw0Tn83qCPnUFObnOc-IpOeRngfSfXkP3aIEh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAY_TCCQACImf__________gmlkgnY0gmlwhF_ZepaEcXVpY4IjjYlzZWNwMjU2azGhAx40S7XpXa_GS9tQvYwp2tdZWYYASCYGaSz_ptyRikAxiHN5bmNuZXRzAIN0Y3CCI4yDdWRwgiOM
      - --execution-endpoint=http://jbc-execution:8551
      - --min-sync-peers=0
      - --accept-terms-of-use
    volumes:
      - ./data/prysm:/data
      - ./config:/config
    ports:
      - 0.0.0.0:13000:13000/tcp
      - 0.0.0.0:13000:13000/udp
    restart: always